---
- name: Check for Connection
  shell: |
    while true; do ping -c1 {{ host_management_ip }} > /dev/null && break; done

- name: Allow time for reboot
  wait_for:
    timeout: 120
  delegate_to: localhost

- name: Join host to vCenter
  community.vmware.vmware_host:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    datacenter_name: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    esxi_hostname: "{{ esxi_hostname }}"
    esxi_username: "{{ esxi_username }}"
    esxi_password: "{{ root_password }}"
    validate_certs: no
    state: present
  delegate_to: localhost

- name: Add host to dVSwitch
  community.vmware.vmware_dvs_host:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    validate_certs: no
    switch_name: "{{ dvswitch_name }}"
    vmnics: 
      - vmnic0
    state: present
  delegate_to: localhost

- name: Migrate from vSSwitch to dVSwitch
  community.vmware.vmware_migrate_vmk:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    validate_certs: no
    device: vmk0
    current_switch_name: "{{ vsswitch_name }}"
    current_portgroup_name: "Management Network"
    migrate_switch_name: "{{ dvswitch_name }}"
    migrate_portgroup_name: "{{ vmk_mgmt_pg }}"
  delegate_to: localhost

- name: Remove vSwitch0
  community.vmware.vmware_vswitch:  
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    validate_certs: no
    switch_name: "{{ vsswitch_name }}"
    state: absent
  delegate_to: localhost

- name: Add both uplinks to dVSwitch
  community.vmware.vmware_dvs_host:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    validate_certs: no
    switch_name: "{{ dvswitch_name }}"
    vmnics: 
      - vmnic0
      - vmnic1
    state: present
  delegate_to: localhost

- name: Add vMotion vmkernel port
  community.vmware.vmware_vmkernel:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    validate_certs: no
    dvswitch_name: "{{ dvswitch_name }}"
    portgroup_name: "{{ vmk_vmotion_pg }}"
    network:
      type: static
      ip_address: "{{ vmk_vmotion_ip }}"
      subnet_mask: 255.255.255.0
    state: present
    enable_vmotion: True
  delegate_to: localhost

- name: Add vSAN vmkernel port
  community.vmware.vmware_vmkernel:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    validate_certs: no
    dvswitch_name: "{{ dvswitch_name }}"
    portgroup_name: "{{ vmk_vsan_pg }}"
    network:
      type: static
      ip_address: "{{ vmk_vsan_ip }}"
      subnet_mask: 255.255.255.0
    state: present
    enable_vsan: True
  delegate_to: localhost

- name: Add iSCSI vmkernel port
  community.vmware.vmware_vmkernel:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    validate_certs: no
    dvswitch_name: "{{ dvswitch_name }}"
    portgroup_name: "{{ vmk_iscsia_pg }}"
    network:
      type: static
      ip_address: "{{ vmk_iscsia_ip }}"
      subnet_mask: 255.255.255.0
    state: present
  delegate_to: localhost

- name: Add iSCSI vmkernel port
  community.vmware.vmware_vmkernel:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    validate_certs: no
    dvswitch_name: "{{ dvswitch_name }}"
    portgroup_name: "{{ vmk_iscsib_pg }}"
    network:
      type: static
      ip_address: "{{ vmk_iscsib_ip }}"
      subnet_mask: 255.255.255.0
    state: present
  delegate_to: localhost

- name: Add NFS vmkernel port
  community.vmware.vmware_vmkernel:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    validate_certs: no
    dvswitch_name: "{{ dvswitch_name }}"
    portgroup_name: "{{ vmk_nfs_pg }}"
    network:
      type: static
      ip_address: "{{ vmk_nfs_ip }}"
      subnet_mask: 255.255.255.0
    state: present
  delegate_to: localhost

- name: Configure NTP
  community.vmware.vmware_host_ntp:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    validate_certs: no
    ntp_servers:
      - "{{ ntp_server }}"
  delegate_to: localhost

- name: Enable Software iSCSI Adapter
  community.vmware.vmware_host_iscsi:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    validate_certs: no
    state: enabled
  delegate_to: localhost
