---
  - name: Create Datacenter
    community.vmware.vmware_datacenter:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      datacenter_name: "{{ datacenter_name }}"
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Create Cluster
    vmware_cluster:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      datacenter_name: "{{ datacenter_name }}"
      cluster_name: "{{ cluster_name }}"
      enable_ha: true
      enable_drs: true
      enable_vsan: false
      validate_certs: no
    delegate_to: localhost

  - name: Enable EVC Mode
    community.vmware.vmware_evc_mode:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      datacenter_name: "{{ datacenter_name }}"
      cluster_name: "{{ cluster_name }}"
      evc_mode: "{{ evc_mode }}"
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Create Folders
    community.vmware.vcenter_folder:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      datacenter_name: "{{ datacenter_name }}"
      folder_name: "{{ item }}"
      folder_type: vm
      state: present
      validate_certs: no
    loop: "{{ vm_folders }}"
    delegate_to: localhost

  - name: Create dvSwitch
    community.vmware.vmware_dvswitch:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      datacenter_name: "{{ datacenter_name }}"
      switch: "{{ dvswitch_name }}"
      version: 7.0.0
      mtu: 1600
      uplink_quantity: 2
      discovery_protocol: cdp
      discovery_operation: both
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Configure Uplink portgroup
    vmware_dvswitch_uplink_pg:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      name: "{{ dvuplinks_name }}"
      switch: "{{ dvswitch_name }}"
      advanced:
        port_config_reset_at_disconnect: True
        block_override: True
        vendor_config_override: False
        vlan_override: False
        netflow_override: False
        traffic_filter_override: False
      vlan_trunk_range:
        - '0-4094'
      netflow_enabled: False
      block_all_ports: False
      validate_certs: no
    delegate_to: localhost

  - name: Create VLAN portgroup
    community.vmware.vmware_dvs_portgroup:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      switch_name: "{{ dvswitch_name }}"
      portgroup_name: "{{ vmk_mgmt_pg }}"
      vlan_id: "{{ vmk_pg_mgmt_vlan }}"
      num_ports: 8
      port_binding: static
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Create VLAN portgroup
    community.vmware.vmware_dvs_portgroup:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      switch_name: "{{ dvswitch_name }}"
      portgroup_name: "{{ vmk_trust_pg }}"
      vlan_id: "{{ vmk_trust_pg_vlan }}"
      num_ports: 8
      port_binding: static
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Create VLAN portgroup
    community.vmware.vmware_dvs_portgroup:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      switch_name: "{{ dvswitch_name }}"
      portgroup_name: "{{ vmk_vmotion_pg }}"
      vlan_id: "{{ vmk_vmotion_pg_vlan }}"
      num_ports: 8
      port_binding: static
      teaming_policy:
        load_balance_policy: loadbalance_loadbased
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Create VLAN portgroup
    community.vmware.vmware_dvs_portgroup:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      switch_name: "{{ dvswitch_name }}"
      portgroup_name: "{{ vmk_vsan_pg }}"
      vlan_id: "{{ vmk_vsan_pg_vlan }}"
      num_ports: 8
      port_binding: static
      teaming_policy:
        load_balance_policy: loadbalance_loadbased
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Create VLAN portgroup
    community.vmware.vmware_dvs_portgroup:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      switch_name: "{{ dvswitch_name }}"
      portgroup_name: "{{ vmk_iscsia_pg }}"
      vlan_id: "{{ vmk_iscsia_pg_vlan }}"
      num_ports: 8
      port_binding: static
      teaming_policy:
        active_uplinks: "Uplink 1"
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Create VLAN portgroup
    community.vmware.vmware_dvs_portgroup:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      switch_name: "{{ dvswitch_name }}"
      portgroup_name: "{{ vmk_iscsib_pg }}"
      vlan_id: "{{ vmk_iscsib_pg_vlan }}"
      num_ports: 8
      port_binding: static
      teaming_policy:
        active_uplinks: "Uplink 2"
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Create VLAN portgroup
    community.vmware.vmware_dvs_portgroup:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      switch_name: "{{ dvswitch_name }}"
      portgroup_name: "{{ vmk_nfs_pg }}"
      vlan_id: "{{ vmk_nfs_pg_vlan }}"
      num_ports: 8
      port_binding: static
      teaming_policy:
        load_balance_policy: loadbalance_loadbased
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Create VLAN portgroup
    community.vmware.vmware_dvs_portgroup:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      switch_name: "{{ dvswitch_name }}"
      portgroup_name: "{{ vmk_tep_pg }}"
      vlan_id: "{{ vmk_tep_pg_vlan }}"
      num_ports: 8
      port_binding: static
      teaming_policy:
        load_balance_policy: loadbalance_loadbased
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Create VLAN portgroup
    community.vmware.vmware_dvs_portgroup:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      switch_name: "{{ dvswitch_name }}"
      portgroup_name: "{{ vmk_uplink1_pg }}"
      vlan_id: "{{ vmk_uplink1_pg_vlan }}"
      num_ports: 8
      port_binding: static
      teaming_policy:
        active_uplinks: "Uplink 1"
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Create VLAN portgroup
    community.vmware.vmware_dvs_portgroup:
      hostname: "{{ vcsa_hostname }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      switch_name: "{{ dvswitch_name }}"
      portgroup_name: "{{ vmk_uplink2_pg }}"
      vlan_id: "{{ vmk_uplink2_pg_vlan }}"
      num_ports: 8
      port_binding: static
      teaming_policy:
        active_uplinks: "Uplink 2"
      state: present
      validate_certs: no
    delegate_to: localhost
